[package]
name = "voxels"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bevy_screen_diagnostics = "0.4.0"
rand = "0.8.0"
bevy_spectator = "0.4"
bevy_atmosphere = "0.8.1"
bevy_debug_grid = "0.3"


[profile.dev.package."*"]
opt-level = 3